### ISSUE TITLE
Download button not showing

### ISSUE THREAD

**Issue by gacolitti** [shafayetShafee/downloadthis#9]
I successfully installed the extension using:

```
quarto add shafayetShafee/downloadthis
```

Then tried your example quarto document:

```
---
title: "Downloadthis Example"
author: Shafayet Khan Shafee
date: last-modified
format: 
  html:
    code-tools: true
embed-resources: true
---

## Downloading png file

Using `{{{< downloadthis files/quarto.png >}}}`, you can create the following download buttons that downloads the logo of quarto embedded within this rendered html document,

{{< downloadthis files/quarto.png >}}
```

But the download button does not appear in the rendered HTML:

![CleanShot 2024-01-26 at 11 21 39](https://github.com/shafayetShafee/downloadthis/assets/29231016/36aeff9b-670d-47ea-bd4f-a23cb2403c2a)

**Comment by shafayetShafee** [comment]
Uhm, I can't reproduce the problem you are facing. I am getting the button and can download the file. And tried with both quarto version `1.3.353` and version `1.4.547`. Everything works fine!

Can you confirm there's a `quarto.png` file in a `files` directory? Because if there's no `quarto.png` in that `files`, that is, `files/quarto.png` does not exist, only then this extension will skip adding the buttons and  print the message `Cannot open file files/quarto2.png | Skipping adding buttons`.

**Comment by gacolitti** [comment]
The issue was the `_extensions` directory was not in the correct location.
